Bp 2323 buckaroo subscriptions
buckaroo-it/WooCommerce pull request #157
Opened 2023-04-18 14:12 UTC by vegimcarkaxhija

2023-04-18 14:31 UTC, harli91 requested changes

2023-04-18 14:31 UTC, harli91 commented on gateway-buckaroo-sofort.php
> +        $this->addSubscriptionsSupport();
as I sad before you should use hooks/filters so this should be `apply_filter('buckaroo_init_payment_class', $this)` then in your plugin you add  support for subscription

2023-04-18 14:31 UTC, harli91 commented on gateway-buckaroo-sofort.php
> +        if($this->is_subscriptions_enabled() && $this->has_subscription($order_id)){
same here you can do this checking and order in the subscription plugin you just do 
```
$sofortbanking = $this->createDebitRequest($order);
apply_filters('buckaroo_before_payment_request', $order, $sofortbanking);
$response = $sofortbanking->Pay();
return fn_buckaroo_process_response($this, $response);
```

2023-04-19 11:07 UTC, harli91 approved these changes

2023-04-19 11:16 UTC, vegimcarkaxhija commented on gateway-buckaroo.php
> +        }
done

2023-04-20 14:23 UTC, harli91 commented on gateway-buckaroo.php
> +        return (isset($response['result']) && $response['result'] === 'no_subscription') ? null : $response;
why not return the response directly `apply_filters($tag, $value, ...$args);` and in the subscription check we don't return a array but `null`?

2023-05-02 12:01 UTC, harli91 approved these changes

2023-06-20 07:29 UTC, harli91 approved these changes

2023-06-20 07:30 UTC, merged