Bp 3311 add support for woo commerce block based checkout
buckaroo-it/WooCommerce pull request #204
Opened 2024-02-02 09:37 UTC by vegimcarkaxhija

2024-02-02 14:10 UTC, harli91 commented on index.php
> +	return str_starts_with( $name, 'buckaroo' );
what about php 7.4

2024-02-02 14:10 UTC, harli91 commented on index.php
> +function get_credtCard_is_secure() {
these function pollute the global namespace

2024-02-02 15:04 UTC, harli91 commented on assets/js/checkout/creditcard-call-encryption.js
> +                jQuery(document).trigger("encryptedDataChanged", [encryptedCardData]);
why aren't you running the encrypt function directly in react?

2024-02-02 15:06 UTC, harli91 commented on gateway-buckaroo.php
> +//        var_dump($_POST);
remove comment

2024-02-02 15:07 UTC, harli91 commented on index.php
> +	wp_enqueue_script('my-block-script', 'assets/js/dist/blocks.js', array('wp-blocks', 'wp-element'));
maybe name this less generic

2024-02-02 15:23 UTC, vegimcarkaxhija commented on assets/js/checkout/creditcard-call-encryption.js
> +                jQuery(document).trigger("encryptedDataChanged", [encryptedCardData]);
this file is used also for normal checkout without React, than I should create two files that have the same function

2024-02-06 13:15 UTC, harli91 commented on assets/js/blocks/components/BuckarooLabel.js
> +            <img src={image_path} alt='Payment Method' style={{ float: 'right' }} />
set the alt to the payment method name

2024-02-06 13:28 UTC, harli91 requested changes

2024-02-06 13:28 UTC, harli91 commented on assets/js/blocks/gateways/buckaroo_afterpay.js
> +    const [isAdditionalCheckboxChecked, setIsAdditionalCheckboxChecked] = useState(false);
why do we need this state?

2024-02-06 13:28 UTC, harli91 commented on assets/js/checkout/checkout.js
> +      buckaroo_partial_birth_field.toggle(!b2bActive);
what is this field, i cannot se this field added in the php templated

2024-02-06 13:28 UTC, harli91 commented on assets/js/checkout/creditcard-call-encryption.js
> +                jQuery(document).trigger("encryptedDataChanged", [encryptedCardData]);
I think we better separate the code from the normal checkout and the react checkout, if we remove the normal checkout functionality it should not brake the react functionality

2024-02-06 13:28 UTC, harli91 commented on library/common.php
> +function getAllGendersForPaymentMethods(): array {
move this into a class, use proper constants

2024-02-06 13:33 UTC, harli91 commented on assets/js/blocks/gateways/buckaroo_afterpaynew.js
> +    const [isTermsAccepted, setIsTermsAccepted] = useState(false);
why do you need this state?

2024-02-06 13:34 UTC, harli91 commented on assets/js/blocks/gateways/buckaroo_afterpaynew.js
> +            case 'terms':
why do you need this swich?

2024-02-06 13:35 UTC, harli91 commented on index.php
> +function starts_with(string $haystack, string $needle): bool {
don't pollute the global namespace

2024-02-06 13:36 UTC, harli91 commented on assets/js/blocks/partials/buckaroo_gender.js
> +        return translations[key] || key;
maybe set the key to capitalize when you return it

2024-02-06 13:38 UTC, harli91 commented on gateway-buckaroo-billink.php
> +            if(!in_array($this->request('buckaroo-billink-gender'), ["Male","Female","Unknown"])) {
what about the value further down the line, i don't see it changed

2024-02-06 13:41 UTC, harli91 commented on assets/js/blocks/partials/buckaroo_terms_and_condition.js
> +        onCheckboxChange(!isChecked ? 'On' : null);
why do you need to set it here as 'On'?

2024-02-06 14:12 UTC, harli91 commented on assets/js/blocks/index.js
> +    const [additionalCheckboxChange, setAdditionalCheckboxChange] = useState('');
split these states into providers for each payment method, a massive global state will be hard to maintain and debug

2024-02-07 15:43 UTC, harli91 commented on assets/js/blocks/components/BuckarooClientSideEncryption.js
> +const encryptCardData = (cardDetails, onEncryptedDataChange) => {
why aren't you using a async function here? and return the encrypted result directly?

2024-02-07 15:49 UTC, harli91 commented on library/config.php
> +            'female' => self::GENDER_FEMALE
these have basically the same values, can't you just extract it into a variable?
also why not set `$allGenders = ['buckaroo-klarnakp' => [],'buckaroo-klarnapay' ]` looks a lot cleaner to me

2024-02-07 15:52 UTC, harli91 commented on assets/js/blocks/components/BuckarooClientSideEncryption.js
> +const encryptCardData = (cardDetails, onEncryptedDataChange) => {
also this is a function not a component, so its better if we move it in a helper folder or something similar

2024-02-13 14:20 UTC, harli91 approved these changes

2024-02-13 14:21 UTC, merged