Feature/bp 1262 remove duplicates from gateway buckaroo classes
buckaroo-it/WooCommerce pull request #47
Opened 2022-01-24 18:42 UTC by serpentscode

2022-01-25 09:42 UTC, vladislav-padalka-hys requested changes

2022-01-25 09:42 UTC, vladislav-padalka-hys commented on gateway-buckaroo.php
> +        if ($method != 'afterpay-new' || $method != 'klarna') {
I don't think it's a good idea to place specific payment method implementation into common class
What if we will specific logic to descendants by redefining /extending methods inside them ?

2022-01-25 09:42 UTC, vladislav-padalka-hys commented on gateway-buckaroo.php
> +    public function getProductsInfo($order, $amountDedit, $shippingCosts, $payment_method, $sendImageInfo = null){
that method became to be quite huge and complex 
could you please split it into several logical chunks
also maybe to move specific payment methods logic into corresponding descendants classes ?

2022-01-25 09:55 UTC, serpentscode commented on gateway-buckaroo.php
> +    public function getProductsInfo($order, $amountDedit, $shippingCosts, $payment_method, $sendImageInfo = null){
Yes, I wasn't too happy with the result too, things got a bit chunky and with some specifics. I'll rework this method to split some functionality out, keep most of common code here and move just specific back into each payment method. This also should solve your first input regarding getProductImage..

Thanks!

2022-01-25 09:56 UTC, vladislav-padalka-hys commented on gateway-buckaroo.php
> +    public function getProductsInfo($order, $amountDedit, $shippingCosts, $payment_method, $sendImageInfo = null){
Thank you ! Then result will be really great !

2022-01-31 16:58 UTC, vladislav-padalka-hys approved these changes

2022-02-01 08:38 UTC, merged